Repository wazuh/wazuh-agent, pull requests merged in 2025-01, with the labels that each got.

#507 Remove mock_server.py in favor of the Imposter-based mock server
  .github/actions/clang_format/action.yml
  src/agent/testtool/mock_server/README.md
  src/agent/testtool/mock_server/group_files/invalidYaml.yml
  src/agent/testtool/mock_server/group_files/validYaml.yml
  src/agent/testtool/mock_server/mock_server.py
  src/agent/testtool/mock_server/responses/commands.json
  src/agent/testtool/mock_server/responses/events_stateful.json
  src/agent/testtool/mock_server/responses/events_stateless.json
  src/agent/testtool/mock_server/responses/templates/commands.templates
  src/agent/testtool/mock_server/responses/templates/events_stateful.templates
  src/agent/testtool/mock_server/responses/templates/events_stateless.templates
Labels: type/change

#511 Fixed dependencies for Linux package generation
  packages/debs/amd64/agent/Dockerfile
  src/vcpkg.json
Labels: type/bug

#539 Update GitHub pull request template
  .github/pull_request_template.md
Labels: type/change

#562 Change default SSL verification mode to `none`
  docs/ref/security.md
  etc/config/wazuh-agent.yml
  src/agent/src/main.cpp
  src/cmake/config.cmake
Labels: type/change, module/agent
